# -*- coding: utf-8 -*-
"""ds2_23LC059

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZZom-20m5BnY8JKajAkzeydUADUqnlc8

#SQLiteでデータベース構築
"""

import sqlite3
!pwd

"""## DB作成"""

# 1. DB作成と接続
path = '/content/'
db_name = 'my_sleep_time.sqlite'
con = sqlite3.connect(path + db_name)
print(type(con))

# 2．SQLを実行するためのオブジェクトを取得
cur = con.cursor()

# 3．実行したいSQLを用意する
create_table_mysleep = 'CREATE TABLE mysleep(day, hour, min);'

# 4．SQLを実行する
cur.execute(create_table_mysleep)

"""##データをDBに挿入する

### データをリストで用意する
"""

# 1. データをリストで用意する

sleeptime_list = [
    ('12/14', 3, 15),
    ('12/15', 5, 51),
    ('12/16', 9, 4),
    ('12/17', 7, 39),
    ('12/18', 3, 30),
    ('12/19', 6, 0),
    ('12/20', 4, 52),
    ('12/21', 4, 22),
    ('12/22', 6, 30),
    ('12/23', 8, 55),
    ('12/24', 4, 25),
    ('12/25', 4, 13),
    ('12/26', 6, 7),
    ('12/27', 1, 32),
    ('12/28', 3, 20),
    ('12/29', 12, 0),
    ('12/30', 4, 20),
    ('12/31', 6, 0),
    ('1/1', 7, 0),
    ('1/2', 6, 0),
    ('1/3', 8, 17),
    ('1/4', 10, 49),
    ('1/5', 4, 11),
    ('1/6', 11, 28),
    ('1/7', 8, 24),
    ('1/8', 6, 46),
    ('1/9', 5, 58),
]

"""### データを挿入"""

# 2. データを挿入するSQLを用意
insert_time = "INSERT INTO mysleep VALUES (?, ?, ?);"

# 3．SQLを実行
cur.executemany(insert_time, sleeptime_list)

# 4. DBの確認

# データを取得するSQL
sql_select = 'SELECT * FROM mysleep;'

# SQLを実行
cur.execute(sql_select)

for r in cur:
  print(r)

#6．DBへの接続を閉じる
con.close()