# -*- coding: utf-8 -*-
"""ds2_23LC059

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZZom-20m5BnY8JKajAkzeydUADUqnlc8

#SQLiteでデータベース構築
"""

import sqlite3
!pwd

"""## DB作成"""

# 1. DB作成と接続
path = '/content/'
db_name = 'my_sleep_time.sqlite'
con = sqlite3.connect(path + db_name)
print(type(con))

# 2．SQLを実行するためのオブジェクトを取得
cur = con.cursor()

# 3．実行したいSQLを用意する
create_table_mysleep = 'CREATE TABLE mysleep(day, hour);'

# 4．SQLを実行する
cur.execute(create_table_mysleep)

"""##データをDBに挿入する

### データをリストで用意する
"""

# 1. データをリストで用意する

sleeptime_list = [
    ('12/14', 3),
    ('12/15', 6),
    ('12/16', 9),
    ('12/17', 8),
    ('12/18', 4),
    ('12/19', 6),
    ('12/20', 5),
    ('12/21', 4),
    ('12/22', 7),
    ('12/23', 9),
    ('12/24', 4),
    ('12/25', 4),
    ('12/26', 6),
    ('12/27', 2),
    ('12/28', 3),
    ('12/29', 12),
    ('12/30', 4),
    ('12/31', 6),
    ('1/1', 7),
    ('1/2', 6),
    ('1/3', 8),
    ('1/4', 11),
    ('1/5', 4),
    ('1/6', 11),
    ('1/7', 8),
    ('1/8', 7),
    ('1/9', 6),
]

"""### データを挿入"""

# 2. データを挿入するSQLを用意
insert_time = "INSERT INTO mysleep VALUES (?, ?);"

# 3．SQLを実行
cur.executemany(insert_time, sleeptime_list)

# 4. DBの確認

# データを取得するSQL
sql_select = 'SELECT * FROM mysleep;'

# SQLを実行
cur.execute(sql_select)

for r in cur:
  print(r)

#6．DBへの接続を閉じる
con.close()